import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* SIDEBAR */}
        <Sidebar />

        {/* FEED */}

        {/* WIDGETS */}

        {/* MODAL */}
      </main>
      
    </div>
  )
}
