import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>This is the header</h1>

      
    </div>
  )
}
